---
- include_tasks: pre.yml

- name: Create group {{ pcmk_group.id }}
  xml:
    path: "{{ pcmk_config.path }}"
    xpath: "/cib/configuration/resources/group[@id='{{ pcmk_group.id }}']"
  check_mode: false
  run_once: true

- name: Create resources in group {{ pcmk_group.id }}
  include_tasks: primitive.yml
  vars:
    primitive_parent: '/cib/configuration/resources/group[@id="{{ pcmk_group.id }}"]'
    parent_id: "{{ pcmk_group.id }}"
    primitive: "{{ inner_item.value }}"
    primitive_id: "{{ inner_item.key }}"
  with_dict: "{{ pcmk_group.resources }}"
  run_once: true
  loop_control:
    loop_var: inner_item

- include_tasks: post.yml
